[build-system]
requires = ["setuptools==78.1.1"]
build-backend = "setuptools.build_meta"

[project]
name = "copyreader"
version = "0.1"
authors = [
  {name = "William G.S. Vinning"}
]
dynamic = ["readme"]
dependencies = [
  "langchain-core==1.0.*",
  "pydantic-core==2.41.*",
  "numpy==2.3.*"
]

[project.optional-dependencies]
test = ["pytest==8.4.*"]
app = ["streamlit==1.50.*", "st-annotated-text==4.0.*", "langchain-google-vertexai==3.0.*", "pandas==2.3.*"]
dev = ["copyreader[test,app]", "pre-commit==4.3.*"]

[tool.setuptools.dynamic]
readme = {file = "README.md"}

[tool.setuptools.packages.find]
exclude = []

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
ignore = ["D", "COM812", "S101"]
select = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]

[tool.mypy]
pretty = true
warn_unused_configs = true
check_untyped_defs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["annotated_text.*", "langchain_google_vertexai.*", "streamlit.*"]

[tool.interrogate]
ignore-overloaded-functions = true
fail-under = 90
exclude = ["setup.py", "docs", "build", "copyreader/tests"]
verbose = 2
color = true
generate-badge = ".github/interrogate-badge.svg"
badge-format = "svg"
badge-style = "flat"

[tool.coverage.report]
exclude_lines = [
  "pragma: not covered",
  "@overload",
  "class .*\\bProtocol\\):"
]
